#!/bin/sh

# Run this command after repo checkout to enable git hooks
# git config core.hooksPath .githooks

printf "\nRunning TSC:\n"

yarn tsc

if [[ "$?" == 0 ]]; then
  printf "\t\033[32mTSC Passed \e[0m"
else
  printf "\t\033[41mTSC Failed \e[0m"
  exit 1
fi
