export const routeSelectors = {
  APPLIANCE_STATUS: "**/licensing/appliances/**/status",
  APPLIANCES: "**/licensing/appliances",
  AUTH_TOKENS: "**/identity/auth/tokens",
  CONN_SCHEMA_OPENSTACK: "**/coriolis/**/providers/openstack/schemas/16",
  ENDPOINTS: "**/coriolis/**/endpoints",
  DEPLOYMENTS: "**/coriolis/**/deployments",
  PROJECTS: "**/identity/auth/projects",
  PROVIDERS: "**/coriolis/**/providers",
  REGIONS: "**/coriolis/**/regions",
  TRANSFERS: "**/coriolis/**/transfers",
  ROLE_ASSIGNMENTS: "**/identity/role_assignments*",
  SCHEDULES: "**/coriolis/**/transfers/**/schedules",
  SECRETS: "**/barbican/**/secrets",
  STATUS: "**/licensing/status",
  USER: "**/identity/users/*",
  USERS: "**/identity/users",
};
