name: Build and Test

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install

      - name: Check Typescript
        run: npm run tsc

      - name: Check ESLint
        run: npm run eslint

      - name: Check Prettier
        run: npm run format

      - name: Run unit tests
        run: npm run test

      - name: Install production dependencies
        run: |
          rm -rf node_modules
          npm install --omit=dev

      - name: Build
        env:
          NODE_OPTIONS: "--openssl-legacy-provider"
        run: npm run build
